### ISSUE TITLE
Loadout caching issues

### ISSUE THREAD

**Issue by ajagnanan** [LittleLightForDestiny/littlelight#29] opened 2019-07-12 19:18 UTC
I noticed some caching issues when using multiple devices. If you update loadouts on one device, it takes a while for it to show up on the other. Can you add a force update to the loadout list?

**Comment by marquesinijatinha** [comment] 2019-07-14 16:30
the loadouts are fetched from the server only when you open little light.
this is by design to prevent server abuse.
the way they are developed are not meant to use two devices at the same time, but to switch between one and other.

**Comment by ajagnanan** [comment] 2019-07-14 17:49
I wasn't trying to use them at the same time, but switch from one device to the other. It doesn't look like the cache is expiring at all. I've opened and closed, also force closed the apps all weekend and it still isn't updating.

**Comment by marquesinijatinha** [comment] 2019-07-14 19:10
Hmmm in that case I need to check, it's probably something related to timezones (I check if your local loadout is newer or older than the one in the server before replacing it)

**Comment by ajagnanan** [comment] 2019-07-14 19:13
Ok cool thanks, let me know if you want me to test anything.

**Comment by ajagnanan** [comment] 2019-07-22 15:44
@marquesinijatinha were you able to check this out yet? So far uninstalling and re-installing the app makes it work...

**Comment by marquesinijatinha** [comment] 2019-07-22 16:03
Unfortunately not yet
I'll try to look into this later today or maybe tomorrow

**Comment by marquesinijatinha** [comment] 2019-07-23 18:24
hey @ajagnanan confirmed
it was an issue with the date checking when importing loadouts from the server.
I've already fixed it and will upload it along with the next release (this week, maybe today)

**Comment by ajagnanan** [comment] 2019-07-23 23:33
awesome, thanks for looking. I'll check it out when its available.

**Comment by ajagnanan** [comment] 2019-07-25 21:12
@marquesinijatinha Finally got the app updates, updating loadouts work good now! It looks like deleting doesn't update the local cache. So if I delete a load out on device A, it doesn't delete from device B. Creating a new loadout works.

**Comment by marquesinijatinha** [comment] 2019-07-25 21:23
@ajagnanan that's by design.
If my server security ever gets compromised, you will still have the loadouts on your device.
If you delete the loadout on device A, it will delete on the server, but won't on device B.

**Comment by ajagnanan** [comment] 2019-07-25 21:30
Oh interesting, its just that now I have a few "test" loadouts I was using that are different on each device. Is a force re-sync from the server possible?

**Comment by marquesinijatinha** [comment] 2019-07-26 21:12
Hmmm I have to think about it, maybe something in settings, but I would only make it with a big ass disclaimer telling the users that they could lose data.

**Comment by ajagnanan** [comment] 2019-07-27 00:04
Awesome, I think its a good option to have.

**Comment by marquesinijatinha** [comment] 2019-07-29 19:35
fixed in 1.6.24

**Closed by marquesinijatinha** 2019-07-29 19:35 UTC
