### ISSUE TITLE
Incorrect weapon mapping

### ISSUE THREAD

**Issue by BelugaMullen** [LittleLightForDestiny/littlelight#60] opened 2020-03-05 14:03 UTC
Love the app but I noticed when viewing a weapon, say my bygones, the other weapon rolls that show up often do not correctly navigate to that weapon when selected. It also incorrectly shows masterwork status when viewing other rolls in the same way

**Comment by marquesinijatinha** [comment] 2020-03-05 15:06
I'm not sure I understand... can you elaborate ?

**Comment by BelugaMullen** [comment] 2020-03-07 16:09
When looking at a weapon via the equipment tab, if you have duplicates of that weapon they show as thumbnails that include the perks on the roll including masterwork type. When clicking on one of those thumbnails, particularly the top left or first one in the list, it will not properly navigate to that specific weapon. Instead you end up viewing another duplicate entirely. Attaching images. First one is the weapon, second is scrolled down to view the duplicates. The third one is the weapon that I was mapped to when I clicked on the top left thumbnail. 
![3B4BE27F-A446-4A9C-8EF2-1AAE2204264A](https://user-images.githubusercontent.com/61835833/76146809-13003c00-6064-11ea-8c9c-86df0fb7c730.png)
![3A260CC9-BEA3-4550-BCB9-59019FA288E7](https://user-images.githubusercontent.com/61835833/76146812-1f849480-6064-11ea-95a7-08268c4c4c31.png)
![A2C4EB4B-7D43-4B02-B7F0-9B47E836ACCD](https://user-images.githubusercontent.com/61835833/76146814-24e1df00-6064-11ea-9f02-43cd02d68a53.png)

**Comment by marquesinijatinha** [comment] 2020-03-09 17:19
hmmm that's really weird... I'm gonna check if I'm able to repro it and what could be the cause.
If I'm unable to repro I will probably need some more details.

**Comment by Deathkraft** [comment] 2020-03-17 09:36
I've had same issue. You look through your weapon selections you see all the other copies of same weapon with different perks. You pick the one you want, but it transfers a totally different one.

**Comment by Maluton** [comment] 2020-04-01 14:00
Came here to bring up this same issue. As described above.

**Comment by Aragornking41** [comment] 2020-04-17 15:19
I also enjoy the app but am also having this issue

**Comment by marquesinijatinha** [comment] 2020-04-27 15:57
@Aragornking41 @Maluton @Deathkraft @BelugaMullen can you confirm if this is fixed in the latest version ?

**Comment by Maluton** [comment] 2020-04-28 00:42
> @Aragornking41 @Maluton @Deathkraft @BelugaMullen can you confirm if this is fixed in the latest version ?

Hey @marquesinijatinha this is working perfectly now! Love your work. Also, the new vanguard/crucible icon indicators are great. Keep it up!

**Closed** 2020-04-28 01:18 UTC
